concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "self-hosted-windows"
  url = "https://gitlab.com"
  id = 52271771
  token = "glrt-87cwyj3jKlTV_SH6c_DAi286MQpwOjFidDMxZQp0OjMKdTpqczdxdRg.01.1j0j196s0"
  token_obtained_at = 2026-03-16T08:38:22Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "powershell"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
