sonar.projectKey=brok3n-wings_lpmde
sonar.projectName=La Petite Maison de l'Épouvante
sonar.projectVersion=1.0
# Obligatoire pour SonarCloud : nom de l'organisation GitHub (en minuscules)
sonar.organization=brok3n-wings

sonar.sources=src
sonar.tests=tests
sonar.language=php

sonar.sourceEncoding=UTF-8

# Couverture de code (générée par PHPUnit)
sonar.php.coverage.reportPaths=var/log/cobertura.xml

# Rapport JUnit (résultats de tests)
sonar.php.tests.reportPath=var/log/junit.xml

# Exclusions
sonar.exclusions=vendor/**,var/**,public/index.php
sonar.test.exclusions=vendor/**

# Qualité : seuils
sonar.qualitygate.wait=false
